###Sample in path
annotationPath : "/scratch/xf3/bxs800/analysis/PenX/funannotate"

###Abspath to components
RepeatMasker : "/g/data/xf3/bxs800/miniconda3/envs/SoilCarbon/share/RepeatMasker/RepeatMasker"
RepLib : "/g/data/xf3/bxs800/miniconda3/envs/SoilCarbon/share/RepeatMasker/Libraries/RMRB.fasta"
InterProScan : "/g/data/xf3/bxs800/programs/interpro/interproscan-5.48-83.0/interproscan.sh"









