###Sample in path
untrimmedPath : "/scratch/be39/bxs800/fungalgenomes/rawdata"

trimmedPath  : "/scratch/be39/bxs800/fungalgenomes/trimmeddata"


###Abspath to components
fastqc : "/home/800/bxs800/programs/FastQC/fastqc"

trimmomatic : "/home/800/bxs800/programs/Trimmomatic-0.39/trimmomatic-0.39.jar"

adapters : "/home/800/bxs800/programs/Trimmomatic-0.39/adapters/all_adapters.fa"

spades : "/home/800/bxs800/myapps/SPADES/3.14.1/SPAdes-3.14.1-Linux/bin/spades.py"

buscolin: "/g/data/be39/bxs800/db/busco/ascomycota_odb9"

#Analysis path
spadesPath : "/scratch/be39/bxs800/fungalgenomes/analysis/SPADES"





