###Sample in path
untrimmedPath : "/scratch/xf3/bxs800/data/PenX/RNAseq/untrimmed"

trimmedPath  : "/scratch/xf3/bxs800/data/PenX/RNAseq/trimmed"


###Abspath to components
fastqc : "/home/800/bxs800/programs/FastQC/fastqc"

trimmomatic : "/home/800/bxs800/programs/Trimmomatic-0.39/trimmomatic-0.39.jar"

adapters : "/home/800/bxs800/programs/Trimmomatic-0.39/adapters/all_adapters.fa"

#Analysis path
hisat2 : "/scratch/xf3/bxs800/analysis/PenX/hisat2Index"

trinity : "/scratch/xf3/bxs800/analysis/PenX/trinity"

#hisat2 components

hisat2_refPATH : ["/scratch/xf3/bxs800/analysis/PenX/hisat2Index/PenX_GenomeJW"] 

hisat2_ref : [ "PenX_GenomeJW"]

hisat2_sortT : "4"

hisat2_mapT : "12"

hisat2_indexT : "16"



